In [10]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
from torch.utils.data import Dataset, DataLoader
import numpy as np
import cv2
import os
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from torch.utils.data import WeightedRandomSampler
from PIL import Image
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix
import torchvision.models as models
from tqdm import tqdm
import copy


In [19]:
def save_to_list(path):
    output_root =path
    X = []
    y = []
    l=[]
        
    label_to_index = {
        'AVM': 0,
        'Normal': 1,
        'Ulcer': 2
    }
    print(label_to_index)
    for root, _, files in os.walk(output_root):
        for file in files:
            if file.endswith(".bmp"): 
                input_path = os.path.join(root, file)

                base, ext = os.path.splitext(file)
                new_filename = f"{base}{ext}"
                image = cv2.imread(input_path)

                X.append(image)
                y.append(label_to_index[new_filename.split("_")[0]])
                l.append(new_filename)
    return X, y, l

In [13]:
# https://discuss.pytorch.org/t/balanced-sampling-between-classes-with-torchvision-dataloader/2703/2

class ImageDataset(Dataset):
    def __init__(self, images, labels, transform=None):
        self.images = images
        self.labels = labels
        self.transform = transform 
    
    def __len__(self):
        return len(self.images)
    
    def __getitem__(self, idx):
        image = Image.fromarray(self.images[idx])  
        label = torch.tensor(self.labels[idx], dtype=torch.long) 

        if self.transform:
            image = self.transform(image)
            
        
        return image, label

In [15]:
class ResNet50Transfer(nn.Module):
    def __init__(self, num_classes=3):
        super(ResNet50Transfer, self).__init__()
        self.base_model = models.resnet50(pretrained=True)

        # Freeze all layers (optional: you can unfreeze later for fine-tuning)
        for param in self.base_model.parameters():
            param.requires_grad = False
        
        for name, param in self.base_model.named_parameters():
            if "layer4" in name or "layer3" in name:  # Unfreeze only final block
                param.requires_grad = True

        in_features = self.base_model.fc.in_features  # Usually 2048
        self.base_model.fc = nn.Sequential(
            nn.Linear(in_features, 512),
            nn.ReLU(),
            nn.Dropout(0.4),
            nn.Linear(512, num_classes) 
        )

    def forward(self, x):
        return self.base_model(x)


In [16]:
def train_and_evaluate_full(model, train_loader, test_loader, save_path, epochs=15, learning_rate=0.001, device='cuda' if torch.cuda.is_available() else 'cpu'):
    print(f"Using device: {device}") 
    model.to(device)

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=0.01)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=10)

    best_test_loss = float('inf')
    best_model_weights = copy.deepcopy(model.state_dict())

    for epoch in range(epochs):
        model.train()
        running_loss = 0.0
        correct, total = 0, 0
        all_labels = []
        all_predictions = []

        for images, labels in tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}"):
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            running_loss += loss.item() * images.size(0)
            _, predicted = torch.max(outputs, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
            all_labels.extend(labels.cpu().numpy())
            all_predictions.extend(predicted.cpu().numpy())

        train_loss = running_loss / total
        train_acc = correct / total
        train_precision = precision_score(all_labels, all_predictions, average='weighted', zero_division=0)
        train_recall = recall_score(all_labels, all_predictions, average='weighted', zero_division=0)
        train_f1 = f1_score(all_labels, all_predictions, average='weighted', zero_division=0)

        # Evaluation on test set
        model.eval()
        test_loss = 0.0
        test_correct, test_total = 0, 0
        test_labels, test_predictions = [], []

        with torch.no_grad():
            for images, labels in test_loader:
                images, labels = images.to(device), labels.to(device)
                outputs = model(images)
                loss = criterion(outputs, labels)

                test_loss += loss.item() * images.size(0)
                _, predicted = torch.max(outputs, 1)
                test_correct += (predicted == labels).sum().item()
                test_total += labels.size(0)
                test_labels.extend(labels.cpu().numpy())
                test_predictions.extend(predicted.cpu().numpy())

        test_loss /= test_total
        test_acc = test_correct / test_total
        test_precision = precision_score(test_labels, test_predictions, average='weighted', zero_division=0)
        test_recall = recall_score(test_labels, test_predictions, average='weighted', zero_division=0)
        test_f1 = f1_score(test_labels, test_predictions, average='weighted', zero_division=0)

        print(f"Epoch {epoch+1}/{epochs}")
        print(f"Train Loss: {train_loss:.4f}, Acc: {train_acc:.4f}, Precision: {train_precision:.4f}, Recall: {train_recall:.4f}, F1: {train_f1:.4f}")
        print(f"Test  Loss: {test_loss:.4f}, Acc: {test_acc:.4f}, Precision: {test_precision:.4f}, Recall: {test_recall:.4f}, F1: {test_f1:.4f}")

        scheduler.step()

        # Save best model based on test loss
        if test_loss < best_test_loss:
            best_test_loss = test_loss
            best_model_weights = copy.deepcopy(model.state_dict())
            print("Best model updated!")

    # Load best model for final evaluation
    model.load_state_dict(best_model_weights)
    torch.save(model.state_dict(), save_path)
    print(f"Best model saved as {save_path}'") # rozszerzenie .pth

    # Final evaluation on test set
    model.eval()
    correct, total = 0, 0
    all_labels = []
    all_predictions = []

    with torch.no_grad():
        for images, labels in test_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
            all_labels.extend(labels.cpu().numpy())
            all_predictions.extend(predicted.cpu().numpy())

    test_acc = correct / total
    test_precision = precision_score(all_labels, all_predictions, average='weighted', zero_division=0)
    test_recall = recall_score(all_labels, all_predictions, average='weighted', zero_division=0)
    test_f1 = f1_score(all_labels, all_predictions, average='weighted', zero_division=0)
    test_conf_matrix = confusion_matrix(all_labels, all_predictions)

    print("\n Final Test Evaluation:")
    print(f"Accuracy: {test_acc:.4f}, Precision: {test_precision:.4f}, Recall: {test_recall:.4f}, F1: {test_f1:.4f}")
    print("Confusion Matrix:\n", test_conf_matrix)

    return model


In [ ]:
X, y, l = save_to_list("output_samples2")

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=123, stratify=y)
X_test, X_val, y_test, y_val = train_test_split(X_test, y_test, test_size=0.5, random_state=123, stratify=y_test)

In [14]:
train_transform = transforms.Compose([
    transforms.Resize((224, 224)),          
    transforms.RandomRotation((-180,180)),  
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),                  
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

test_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])  # do testów - bez zmian


train_dataset = ImageDataset(X_train, y_train, transform=train_transform)
test_dataset = ImageDataset(X_test, y_test, transform=test_transform)

class_counts = np.bincount(y)  
class_weights = 1.0 / class_counts 

sample_weights_tr = [class_weights[label] for label in y_train]
sample_weights_ts = [class_weights[label] for label in y_test]

samplertr = WeightedRandomSampler(sample_weights_tr, num_samples= len(sample_weights_tr), replacement=True)
#samplerts = WeightedRandomSampler(sample_weights_ts, num_samples= len(sample_weights_ts), replacement=True)

batch_size = 32

train_loader = DataLoader(train_dataset, batch_size=batch_size, sampler = samplertr)

test_loader = DataLoader(test_dataset, batch_size=batch_size)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [17]:
model = ResNet50Transfer(num_classes=3)
trained_model = train_and_evaluate_full(model, train_loader, test_loader, "model_output_samples_25.04.pth")

c:\Users\alapr\AppData\Local\Programs\Python\Python312\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\alapr\AppData\Local\Programs\Python\Python312\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Using device: cuda


Epoch 1/15: 100%|██████████| 20/20 [00:05<00:00,  3.79it/s]


Epoch 1/15
Train Loss: 0.7697, Acc: 0.6453, Precision: 0.6472, Recall: 0.6453, F1: 0.6461
Test  Loss: 26.2028, Acc: 0.5865, Precision: 0.8362, Recall: 0.5865, F1: 0.6081
Best model updated!


Epoch 2/15: 100%|██████████| 20/20 [00:05<00:00,  3.91it/s]


Epoch 2/15
Train Loss: 0.5192, Acc: 0.7865, Precision: 0.7873, Recall: 0.7865, F1: 0.7867
Test  Loss: 3.0275, Acc: 0.7594, Precision: 0.7630, Recall: 0.7594, F1: 0.6950
Best model updated!


Epoch 3/15: 100%|██████████| 20/20 [00:05<00:00,  3.76it/s]


Epoch 3/15
Train Loss: 0.3817, Acc: 0.8475, Precision: 0.8454, Recall: 0.8475, F1: 0.8451
Test  Loss: 0.5777, Acc: 0.7895, Precision: 0.8347, Recall: 0.7895, F1: 0.7978
Best model updated!


Epoch 4/15: 100%|██████████| 20/20 [00:05<00:00,  3.72it/s]


Epoch 4/15
Train Loss: 0.3401, Acc: 0.8973, Precision: 0.8976, Recall: 0.8973, F1: 0.8974
Test  Loss: 0.6681, Acc: 0.7444, Precision: 0.8340, Recall: 0.7444, F1: 0.7618


Epoch 5/15: 100%|██████████| 20/20 [00:05<00:00,  3.72it/s]


Epoch 5/15
Train Loss: 0.2144, Acc: 0.9133, Precision: 0.9128, Recall: 0.9133, F1: 0.9129
Test  Loss: 0.3524, Acc: 0.8571, Precision: 0.8891, Recall: 0.8571, F1: 0.8648
Best model updated!


Epoch 6/15: 100%|██████████| 20/20 [00:05<00:00,  3.69it/s]


Epoch 6/15
Train Loss: 0.2385, Acc: 0.9165, Precision: 0.9164, Recall: 0.9165, F1: 0.9165
Test  Loss: 0.1767, Acc: 0.9098, Precision: 0.9285, Recall: 0.9098, F1: 0.9132
Best model updated!


Epoch 7/15: 100%|██████████| 20/20 [00:05<00:00,  3.71it/s]


Epoch 7/15
Train Loss: 0.1787, Acc: 0.9422, Precision: 0.9431, Recall: 0.9422, F1: 0.9423
Test  Loss: 0.1517, Acc: 0.9323, Precision: 0.9334, Recall: 0.9323, F1: 0.9305
Best model updated!


Epoch 8/15: 100%|██████████| 20/20 [00:05<00:00,  3.74it/s]


Epoch 8/15
Train Loss: 0.1842, Acc: 0.9358, Precision: 0.9371, Recall: 0.9358, F1: 0.9356
Test  Loss: 0.1935, Acc: 0.9173, Precision: 0.9220, Recall: 0.9173, F1: 0.9179


Epoch 9/15: 100%|██████████| 20/20 [00:05<00:00,  3.73it/s]


Epoch 9/15
Train Loss: 0.1512, Acc: 0.9518, Precision: 0.9528, Recall: 0.9518, F1: 0.9521
Test  Loss: 0.1205, Acc: 0.9474, Precision: 0.9468, Recall: 0.9474, F1: 0.9470
Best model updated!


Epoch 10/15: 100%|██████████| 20/20 [00:05<00:00,  3.71it/s]


Epoch 10/15
Train Loss: 0.1037, Acc: 0.9679, Precision: 0.9678, Recall: 0.9679, F1: 0.9678
Test  Loss: 0.1194, Acc: 0.9549, Precision: 0.9543, Recall: 0.9549, F1: 0.9542
Best model updated!


Epoch 11/15: 100%|██████████| 20/20 [00:05<00:00,  3.62it/s]


Epoch 11/15
Train Loss: 0.0949, Acc: 0.9647, Precision: 0.9652, Recall: 0.9647, F1: 0.9647
Test  Loss: 0.1308, Acc: 0.9474, Precision: 0.9493, Recall: 0.9474, F1: 0.9478


Epoch 12/15: 100%|██████████| 20/20 [00:05<00:00,  3.84it/s]


Epoch 12/15
Train Loss: 0.1113, Acc: 0.9695, Precision: 0.9701, Recall: 0.9695, F1: 0.9694
Test  Loss: 0.1242, Acc: 0.9474, Precision: 0.9481, Recall: 0.9474, F1: 0.9467


Epoch 13/15: 100%|██████████| 20/20 [00:05<00:00,  3.71it/s]


Epoch 13/15
Train Loss: 0.1151, Acc: 0.9599, Precision: 0.9600, Recall: 0.9599, F1: 0.9599
Test  Loss: 0.1138, Acc: 0.9624, Precision: 0.9641, Recall: 0.9624, F1: 0.9627
Best model updated!


Epoch 14/15: 100%|██████████| 20/20 [00:05<00:00,  3.69it/s]


Epoch 14/15
Train Loss: 0.0616, Acc: 0.9807, Precision: 0.9807, Recall: 0.9807, F1: 0.9807
Test  Loss: 0.1105, Acc: 0.9549, Precision: 0.9556, Recall: 0.9549, F1: 0.9546
Best model updated!


Epoch 15/15: 100%|██████████| 20/20 [00:05<00:00,  3.69it/s]


Epoch 15/15
Train Loss: 0.0788, Acc: 0.9679, Precision: 0.9679, Recall: 0.9679, F1: 0.9679
Test  Loss: 0.0860, Acc: 0.9624, Precision: 0.9641, Recall: 0.9624, F1: 0.9627
Best model updated!
Best model saved as model_output_samples_25.04.pth'

 Final Test Evaluation:
Accuracy: 0.9624, Precision: 0.9641, Recall: 0.9624, F1: 0.9627
Confusion Matrix:
 [[25  1  0]
 [ 3 83  1]
 [ 0  0 20]]


Do porównania model wytrenowany na zdjęciach z folderu output.

In [20]:
X, y, l = save_to_list("output")

{'AVM': 0, 'Normal': 1, 'Ulcer': 2}


In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=123, stratify=y)
X_test, X_val, y_test, y_val = train_test_split(X_test, y_test, test_size=0.5, random_state=123, stratify=y_test)

In [22]:
train_transform = transforms.Compose([
    transforms.Resize((224, 224)),          
    transforms.RandomRotation((-180,180)),  
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),                  
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

test_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])  # do testów - bez zmian


train_dataset = ImageDataset(X_train, y_train, transform=train_transform)
test_dataset = ImageDataset(X_test, y_test, transform=test_transform)

class_counts = np.bincount(y)  
class_weights = 1.0 / class_counts 

sample_weights_tr = [class_weights[label] for label in y_train]
sample_weights_ts = [class_weights[label] for label in y_test]

samplertr = WeightedRandomSampler(sample_weights_tr, num_samples= len(sample_weights_tr), replacement=True)
#samplerts = WeightedRandomSampler(sample_weights_ts, num_samples= len(sample_weights_ts), replacement=True)

batch_size = 32

train_loader = DataLoader(train_dataset, batch_size=batch_size, sampler = samplertr)

test_loader = DataLoader(test_dataset, batch_size=batch_size)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [23]:
model = ResNet50Transfer(num_classes=3)
trained_model = train_and_evaluate_full(model, train_loader, test_loader, "model_output_simple.pth")

c:\Users\alapr\AppData\Local\Programs\Python\Python312\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\alapr\AppData\Local\Programs\Python\Python312\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Using device: cuda


Epoch 1/15: 100%|██████████| 72/72 [00:16<00:00,  4.26it/s]


Epoch 1/15
Train Loss: 0.4553, Acc: 0.8330, Precision: 0.8335, Recall: 0.8330, F1: 0.8329
Test  Loss: 0.2959, Acc: 0.8864, Precision: 0.8981, Recall: 0.8864, F1: 0.8888
Best model updated!


Epoch 2/15: 100%|██████████| 72/72 [00:16<00:00,  4.43it/s]


Epoch 2/15
Train Loss: 0.2395, Acc: 0.9182, Precision: 0.9182, Recall: 0.9182, F1: 0.9181
Test  Loss: 0.1776, Acc: 0.9493, Precision: 0.9507, Recall: 0.9493, F1: 0.9483
Best model updated!


Epoch 3/15: 100%|██████████| 72/72 [00:16<00:00,  4.39it/s]


Epoch 3/15
Train Loss: 0.1892, Acc: 0.9352, Precision: 0.9358, Recall: 0.9352, F1: 0.9353
Test  Loss: 0.1682, Acc: 0.9331, Precision: 0.9407, Recall: 0.9331, F1: 0.9348
Best model updated!


Epoch 4/15: 100%|██████████| 72/72 [00:16<00:00,  4.43it/s]


Epoch 4/15
Train Loss: 0.1259, Acc: 0.9565, Precision: 0.9566, Recall: 0.9565, F1: 0.9565
Test  Loss: 0.1413, Acc: 0.9554, Precision: 0.9583, Recall: 0.9554, F1: 0.9560
Best model updated!


Epoch 5/15: 100%|██████████| 72/72 [00:16<00:00,  4.43it/s]


Epoch 5/15
Train Loss: 0.1091, Acc: 0.9665, Precision: 0.9667, Recall: 0.9665, F1: 0.9665
Test  Loss: 0.1210, Acc: 0.9594, Precision: 0.9618, Recall: 0.9594, F1: 0.9598
Best model updated!


Epoch 6/15: 100%|██████████| 72/72 [00:16<00:00,  4.40it/s]


Epoch 6/15
Train Loss: 0.0853, Acc: 0.9761, Precision: 0.9762, Recall: 0.9761, F1: 0.9761
Test  Loss: 0.0667, Acc: 0.9817, Precision: 0.9819, Recall: 0.9817, F1: 0.9818
Best model updated!


Epoch 7/15: 100%|██████████| 72/72 [00:16<00:00,  4.47it/s]


Epoch 7/15
Train Loss: 0.0694, Acc: 0.9761, Precision: 0.9761, Recall: 0.9761, F1: 0.9761
Test  Loss: 0.0821, Acc: 0.9777, Precision: 0.9780, Recall: 0.9777, F1: 0.9776


Epoch 8/15: 100%|██████████| 72/72 [00:16<00:00,  4.42it/s]


Epoch 8/15
Train Loss: 0.0477, Acc: 0.9835, Precision: 0.9835, Recall: 0.9835, F1: 0.9835
Test  Loss: 0.0623, Acc: 0.9838, Precision: 0.9837, Recall: 0.9838, F1: 0.9837
Best model updated!


Epoch 9/15: 100%|██████████| 72/72 [00:15<00:00,  4.62it/s]


Epoch 9/15
Train Loss: 0.0347, Acc: 0.9891, Precision: 0.9891, Recall: 0.9891, F1: 0.9891
Test  Loss: 0.0751, Acc: 0.9797, Precision: 0.9800, Recall: 0.9797, F1: 0.9798


Epoch 10/15: 100%|██████████| 72/72 [00:15<00:00,  4.57it/s]


Epoch 10/15
Train Loss: 0.0348, Acc: 0.9900, Precision: 0.9900, Recall: 0.9900, F1: 0.9900
Test  Loss: 0.0734, Acc: 0.9797, Precision: 0.9800, Recall: 0.9797, F1: 0.9798


Epoch 11/15: 100%|██████████| 72/72 [00:15<00:00,  4.65it/s]


Epoch 11/15
Train Loss: 0.0412, Acc: 0.9852, Precision: 0.9852, Recall: 0.9852, F1: 0.9852
Test  Loss: 0.0695, Acc: 0.9797, Precision: 0.9800, Recall: 0.9797, F1: 0.9798


Epoch 12/15: 100%|██████████| 72/72 [00:16<00:00,  4.40it/s]


Epoch 12/15
Train Loss: 0.0234, Acc: 0.9930, Precision: 0.9930, Recall: 0.9930, F1: 0.9930
Test  Loss: 0.0675, Acc: 0.9797, Precision: 0.9800, Recall: 0.9797, F1: 0.9798


Epoch 13/15: 100%|██████████| 72/72 [00:15<00:00,  4.56it/s]


Epoch 13/15
Train Loss: 0.0392, Acc: 0.9856, Precision: 0.9856, Recall: 0.9856, F1: 0.9856
Test  Loss: 0.0614, Acc: 0.9817, Precision: 0.9817, Recall: 0.9817, F1: 0.9817
Best model updated!


Epoch 14/15: 100%|██████████| 72/72 [00:16<00:00,  4.48it/s]


Epoch 14/15
Train Loss: 0.0446, Acc: 0.9870, Precision: 0.9870, Recall: 0.9870, F1: 0.9870
Test  Loss: 0.0814, Acc: 0.9777, Precision: 0.9781, Recall: 0.9777, F1: 0.9778


Epoch 15/15: 100%|██████████| 72/72 [00:15<00:00,  4.69it/s]


Epoch 15/15
Train Loss: 0.0438, Acc: 0.9865, Precision: 0.9865, Recall: 0.9865, F1: 0.9865
Test  Loss: 0.0507, Acc: 0.9899, Precision: 0.9900, Recall: 0.9899, F1: 0.9898
Best model updated!
Best model saved as model_output_simple.pth'

 Final Test Evaluation:
Accuracy: 0.9899, Precision: 0.9900, Recall: 0.9899, F1: 0.9898
Confusion Matrix:
 [[ 96   4   0]
 [  0 322   1]
 [  0   0  70]]
